<img src="https://images.efollett.com/htmlroot/images/templates/storeLogos/CA/864.gif" style="float: right;"> 




# ECON611
### Final Exam -  Study Guide 
- The purpose of this study guide is to give you an idea of the topics and type of questions you will see in the final exam.

### 1. Git 
---
- What are the steps you will take to ignore files in git?

ANS: 
1. nano .gitigonore
2. add files that you want to ignore such as DS_store, thumb.db
3. save and close
4. git status
5. git add .gitignore
6. git commit -m "files to ignore"
7. git status

### 2. Command line
---

In the following sequence what is the output of the last ``ls`` command? 
```
pwd 
    GIVES YOU THIS OUTPUT: /Users/mario/data
ls
    GIVES YOU THIS OUTPUT: regressions.py
mkdir combine
mv regressions.py combine
mv combine/regressions.py        ../regressions\_complete.py
ls 
```
ANS: combine

### 3.1 Command line
---

In the example below, what does ``cp`` do when given several filenames and a directory name?
```
$ mkdir just_in_case
$ cp study_guide_1.txt my_studies.txt just_in_case/
```
ANS:
copy the target file, study_guide1.txt, to "just_in_case" folder and also rename it as "my_studies.txt"


### 3.2 Command line
---

In the example below, what does ``cp`` do when given three or more file names?

```
$ cp study_guide_1.txt my_studies.txt python_ideas.txt
```

ANS: when given a directory name, cp will copy 3 files to the named directory.
if given only 3 names, cp will respond an error because it is ecpecting a directory name as the destination

### 4. Functions with strings
---
Def a function that given a sentence it returns the same sentece in reverse words and caps the first letter of each word
```
reverseWords("The most brilliant people I have met are those who like ice cream")

should return => Cream Ice Like Who Those Are Met Have I People Brilliant Most The
```

In [45]:
#ANS:

def reverseWords(x):
    words = x.split(" ")
    words = words[-1::-1]
    output = " ".join(words)
    return output.title()

reverseWords("The most brilliant people I have met are those who like ice cream")    
    

'Cream Ice Like Who Those Are Met Have I People Brilliant Most The'

### 5. Functions + Math
---
Def a function that calculates the volume of a sphere with a radius ``r`` where the equation is $${4\over 3}\pi{r}^{3} $$ you should import the pi function from math as 
```
import math
```
In the exam I will give you the hint about what function you need to import 

In [59]:
#ANS:

import math
def question5(r):
    return 4/3 * math.pi * r**3

question5(2)


33.510321638291124

### 6. Functions + strings + list comp
---

Write a function that:

1. Accepts a list of movies and a category name.
2. Returns the movie names within that category (case-insensitive!)
3. If the category is not in the data, print a message that it does not exist and return None.

Here is an example for your input

```
movies = [
{
"name": "Usual Suspects", 
"imdb": 7.0,
"category": "Thriller"
},
{
"name": "Hitman",
"imdb": 6.3,
"category": "Action"
},
{
"name": "Dark Knight",
"imdb": 9.0,
"category": "Adventure"
},
{
"name": "The Help",
"imdb": 8.0,
"category": "Drama"
}]
```

In [84]:
#ANS:

movies = [
{
"name": "Usual Suspects", 
"imdb": 7.0,
"category": "Thriller"
},
{
"name": "Hitman",
"imdb": 6.3,
"category": "Action"
},
{
"name": "Dark Knight",
"imdb": 9.0,
"category": "Adventure"
},
{
"name": "The Help",
"imdb": 8.0,
"category": "Drama"
}]

#print([i['name'] for i in movies if i['category'] == 'Action'])

def name1(x,y):
    pick = [i['name'] for i in x if i['category'].lower() == y.lower()]
    if pick == []:
        print('%s does not exist'%(y))
        return None
    else:
        return pick

name1(movies,'action')


['Hitman']

### 6. Classes 
---

Def a class that calculates the volume of a sphere with a radius ``r`` where the equation is $${4\over 3}\pi{r}^{3} $$ you should import the pi function from math as 
```
import math
```
In the exam I will give you the hint about what function you need to import 

In [75]:
#ANS:

import math
class sphere:
    def __init__(self,radius): 
        self.radius = radius
    def volume(self):  #method
        return 4/3 * math.pi * self.radius ** 3


In [87]:
k = sphere(2)
k.volume()

33.510321638291124

### 7. Classes 
---

1. Define a class called Dinner. 
2. Its ```__init__()``` method should have two arguments:self and menu (where menu is a string). 
3. Add a method called dinner_menu_price.
    - It will involve a if statement:
        - if "dinner menu 1" print "Your dinner choice:", menu, "will be 120.00", 
        - if "menu 2" print "Your dinner choice:", menu, "will be 144.60", 
        - else print "Error in dinner menu".

In [80]:
#ANS:
class Dinner:
    def __init__(self, menu):
        self.menu = menu
    def dinner_menu_price(self):
        if self.menu == 'menu 1':
            return 'Your dinner choice: ' + self.menu + ' will be 120.00'
        elif self.menu == 'menu 2':
            return 'Your dinner choice: ' + self.menu + ' will be 144.60'
        else:
            return 'Error in dinner menu'

In [83]:
j = Dinner('menu 2')

j.dinner_menu_price()


'Your dinner choice: menu 2 will be 144.60'

### 8. Classes 
---
Define a class to calculates the wage of an employee by
1. Define a class called Employee. 
2. Its ```__init__()``` method should have 3 arguments: self, employee name, wage .  
3. Add a method calculate_wage that takes self, hours, wage.
    - it will return the number of hours * wage
4. Create a new class, PartTimeEmployee, that inherits from Employee
5. Override the PartTimeEmployee method it should take self, hours, wage and returns hours * wage/2. 

In [91]:
#5. Override the calculate_wage method it should take self, hours, wage and returns hours * wage/2.
#ANS:
class Employee:
    def __init__(self, n, w):
        self.name = n
        self.wage = w
    def calculate_wage(self, h):
        self.hours = h
        return self.hour * self.wage

In [95]:
f = Employee("Jack", 10)
f.calculate_wage(3)


30

In [100]:
class PartTimeEmployee(Employee):
    def __init__(self, n, w):
        Employee.__init__(self, n, w)
    def calculate_wage(self, h):
        self.hours = h
        return self.hours * self.wage / 2



In [103]:
j = PartTimeEmployee('Peter', 20)
j.calculate_wage(3)

30.0

### 9. Numpy + Matrices 
---
1. Translate the following equation into a numpy operations
$${2I} + {3A} + {AB}$$
2. Define two 2X2 matrices.
3. Define an identity matrix (I = np.eye(2))
4. Use np.matmul(A, B) for the matrix multiplication
5. You don't need to do the math



In [111]:
#ANS:
import numpy as np
matrix = 2 * I + 3 * A + np.matmul(A, B) #1

A = np.array([[1,2],[2,4]]) #2
print(A)

[[1 2]
 [2 4]]


In [115]:
#ANS:
I = np.eye(2) #3
2 * I

array([[2., 0.],
       [0., 2.]])

In [113]:
#ANS:
B = np.array([[4,1],[2,2]]) #4
np.matmul(A, B)

array([[ 8,  5],
       [16, 10]])

In [114]:
#ANS:

### SQL
---
Given this Entity Relation Diagram (Sample Database)

<p align="center">
  <img src="../../img/sql_schema.png" width="1000" height="1500">
</p>


[Image from W3Schools](https://www.chegg.com/homework-help/questions-and-answers/link-w3schools-relationship-diagram-needed-questions-1-implementing-relational-database-co-q38045137)


### 10 Write a SQL query that:
---
1. Retrieves the top 3 orders by number of items ordered

#ANS: 
SELECT top 3 * 
FROM OrderDetails 
order by Quantity desc;  

### 11 Write a SQL query that:
---
1. Retrieves the oldest 5 orders

SELECT top 5 * 
from orders 
order by orderdate;

### 12 Write a SQL query that:
---
1. Retrieves the 5 most recent orders.

select top 5 * 
from orders 
order by orderdate desc; 

limit 5;

### 13. Pandas
---
1. Define a function that takes in a dataset, a list of columns, and one column of interest as arguments
2. Returns the count, mean, std, min, 25%, 50%, 75%, max values

In [ ]:
import pandas as pd
def extract(path):
    dataset = pd.read_csv(path)
    print(list(dataset.columns))
    print('\n')
    print(dataset.describe().T)
    print('\n')
    return dataset

def describle()


### 14. Pandas
---
Explain the differences of the following methods of indexing in python
1. loc
2. .iloc
3. .ix

.loc indexes with the labels for rows and columns
.iloc indexes with the integer positions for rows and columns
.ix indexes with both labels and integer positions